name = "astro-marketplace"
compatibility_date = "2025-01-09"
main = "dist/index.js"

# Replace placeholder IDs with real ones after running:
#   wrangler d1 create astro_marketplace
#   wrangler kv:namespace create SESSION

[[d1_databases]]
binding = "DB"
database_name = "astro_marketplace"
database_id = "REPLACE_WITH_PROD_D1_ID"

[[kv_namespaces]]
binding = "SESSION"
id = "REPLACE_WITH_KV_NAMESPACE_ID"

[vars]
SESSION_SECRET = "REPLACE_WITH_SECURE_SECRET"
# Set via `wrangler secret put SESSION_SECRET` for production.
